<?php

namespace AppBundle\Repository;

/**
 * ReservationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReservationRepository extends \Doctrine\ORM\EntityRepository
{

    public function findReservationEnCours()
    {
        $date = new \DateTime();
        $from = new \DateTime($date->format("Y-m-d")." 00:00:00");
        $to = new \DateTime($date->format("Y-m-d")." 23:59:59");

        $query = $this->createQueryBuilder('r')
            ->select('r')
            ->where('r.dateDebut <= :from')
            ->andWhere('r.dateFin >= :to')
            ->setParameter('from', $from)
            ->setParameter('to', $to);

        return $query->getQuery()->getResult();
    }

    public function findReservationEnRetard()
    {
        $date = new \DateTime();
        $from = new \DateTime($date->format("Y-m-d")." 00:00:00");
        $to = new \DateTime($date->format("Y-m-d")." 23:59:59");

        $query = $this->createQueryBuilder('r')
            ->select('r')
            ->where('r.dateFin <= :from')
            ->andWhere("r.etat != 'Terminé'")
            ->setParameter('from', $from);
        return $query->getQuery()->getResult();
    }

}
